source 'https://rubygems.org'

gem 'activeadmin-mongoid', path: '../'
gem 'activeadmin', '~> 1.3.0'

# Test app stuff

gem 'rails', '~> 5.1.6'

gem 'pry'

gem 'devise'

gem 'mongoid', '~> 6.0.3', require: true
gem 'kaminari', '~> 1.0'
gem 'kaminari-mongoid'
gem 'ransack', '< 1.8.7'

gem 'sprockets', '>= 3.7.2'

# Gems used only for assets and not required
# in production environments by default.
gem 'sass-rails'
gem 'coffee-rails'

# See https://github.com/sstephenson/execjs#readme for more supported runtimes
# gem 'therubyracer', :platforms => :ruby
gem 'uglifier'

gem 'jquery-rails'
# gem "jquery-rails", "~> 2.3.0"

gem 'jquery-ui-rails'
gem 'jslint'

group :test do
  gem 'capybara'
  gem 'poltergeist'
  gem 'launchy'
  gem 'simplecov', require: false
end
