source 'https://rubygems.org'

gem 'activeadmin-mongoid', path: '../'

gem 'rails', '~> 5.1.6'

gem 'pry'

gem 'devise'

gem 'ransack-mongoid', github: 'activerecord-hackery/ransack-mongoid'

gem 'sprockets', '>= 3.7.2'

# Gems used only for assets and not required
# in production environments by default.
gem 'coffee-rails'
gem 'sass-rails'

# See https://github.com/sstephenson/execjs#readme for more supported runtimes
# gem 'therubyracer', :platforms => :ruby
gem 'uglifier'

gem 'jquery-rails'

gem 'jquery-ui-rails'
gem 'jslint'

group :test do
  gem 'capybara'
  gem 'launchy'
  gem 'poltergeist'
  gem 'simplecov', require: false
end
